### ISSUE TITLE
add modifications for v2 encoding of pseudonymization

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/infsec#11]
@SmalsJulien

see also https://be-ehealth-standards.atlassian.net/issues/ESI-862 for the original mail:

The following things were agreed:
• If a field is pseudonymized, the following possibilities are allowed. The intention is of course that everyone migrates to a prefixed form
o {base64 json string}
o urn:be:fgov:pseudo:v1:{base64 json string}
o urn:be:fgov:pseudo:v2:{SEC1}:{transitInfo}
o urn:be:fgov:pseudo-encrypted:v1:{KID}:{JWE}
• An extension will always be added to such a pseudonymized field
o url": https://www.ehealth.fgov.be/standards/fhir/infsec/StructureDefinition/be-ext-pseudonymization
o extensions:
 marker: true
 format: direct|encrypted default value : direct
 version: 1 |2 default version: 1

• When pseudo-encrypted is used, an extension will always be added at the resource level
o Id: {KID}
o url: https://www.ehealth.fgov.be/standards/fhir/infsec/StructureDefinition/be-ext-key-pseudonymization
o extensions:
 key: urn:be:fgov:pseudo:v2:{SEC1}:{transitInfo} note of course an extension is also added here.

**Comment by bdc-ehealth** [comment]
WG: the comment above https://github.com/hl7-be/infsec/issues/11#issue-2486655620 is not an agreement of the HL7 workgroup but from the technical people involved (developers of the backend systems).

**Comment by HanneVuegen** [comment]
When will this be published?
