### ISSUE TITLE
add new extension for pseudonymization of free text + modifications to existing extension

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/infsec#9]
@SmalsJulien

see: https://github.com/hl7-be/referral/issues/347

**Comment by SmalsJulien** [comment]
Hello,

Perfect, thank you! I will come back to you when we have more information on where the encryption key will be stored (in each FHIR resource or at the parent level).
This analysis will be done during this PI.

**Comment by bdc-ehealth** [comment]
@SmalsJulien : https://build.fhir.org/ig/hl7-be/infsec/branches/issue-9/

**Comment by SmalsJulien** [comment]
Thank you, Bart!

**Comment by bdc-ehealth** [comment]
@SmalsJulien : Hi Julien, I investigated the problem you reported me by phone about how to pseudonymize a long text in a Parameters resource. A Parameters resource does not have an extension section (only DomainResources have it) and so the key extension was not useable for Parameters resources. Therefore I had to move the extension to the .meta section of the Resource. I also investigated the case of contained resources and bundles, and all cases seem to be catered for with this last change.

**Comment by bdc-ehealth** [comment]
@SmalsJulien: after some discussion with Hannes Declercq and Steve Van Reeth: I add the required modifications below:

see also https://be-ehealth-standards.atlassian.net/issues/ESI-862 for the original mail: 

The following things were agreed:
• If a field is pseudonymized, the following possibilities are allowed. The intention is of course that everyone migrates to a prefixed form
o {base64 json string}
o urn:be:fgov:pseudo:v1:{base64 json string}
o urn:be:fgov:pseudo:v2:{SEC1}:{transitInfo}
o urn:be:fgov:pseudo-encrypted:v1:{KID}:{JWE}
• An extension will always be added to such a pseudonymized field
o url": https://www.ehealth.fgov.be/standards/fhir/infsec/StructureDefinition/be-ext-pseudonymization
o extensions:
 marker: true
 format: direct|encrypted default value : direct
 version: 1 |2 default version: 1

• When pseudo-encrypted is used, an extension will always be added at the resource level
o Id: {KID}
o url: https://www.ehealth.fgov.be/standards/fhir/infsec/StructureDefinition/be-ext-key-pseudonymization 
o extensions:
 key: urn:be:fgov:pseudo:v2:{SEC1}:{transitInfo} note of course an extension is also added here.

**Comment by smals-bvv** [comment]
@bdc-ehealth We came across this issue with v2 and we were analyzing how we can implement this in a matter of backwards compatibility.

We are missing guidelines for following use cases:
- What if a resource is being read, what pseudo version should be used for returning a response? Should we default to a certain version? Can a header be helpful/useful to specify which version a client prefers to receive in the responses?
- Should a request with multiple pseudonyms of mixed versions v1 and v2 be blocked?
- If v1 is used in the request, is it mandatory for the response to contain v1 as well?

**Comment by smals-stvar** [comment]
@smals-bvv, I am not a FHIR expert, but here is my point of view.

For the first point, their API contract should specify which format it accept: v1, v2 or both. For the responses, they should decide which format they return: v1 or v2. If they want to give the choice to their clients, they should handle something in the request. For example, something in the “Accept” HTTP header. We should maybe recommend a way to do that (if it is not yet documented).

Second point: it depends on their implantation. But if they accept both, a mix should be accepted in my opinion (even if it is strange for a client to use both formats in the same request).

Third point: they decide what their responses contain. If they decide to return pseudonyms in v2 and if they accept pseudonyms in v1 in their requests, it is not a problem to returns v2 even if the request contains v1.

**Comment by smals-bvv** [comment]
@smals-stvar Thanks for your input.

@bdc-ehealth can something be documented for passing the version in the Accept header? I am quite confident that we as a server will need to be able to support both versions at the same time for different integrators.

We are also wondering why for the pseudo-encrypted the v2 prefix is mandatory, why can't it be v1?
https://build.fhir.org/ig/hl7-be/infsec/branches/issue-9/StructureDefinition-be-ext-key-pseudonymization.html#profile
![image](https://github.com/user-attachments/assets/2689fd16-607d-440a-b3da-320101dfa06c)


Apart from that, we notice duplicate information as the value will contain the prefix and the extension will contain a field for the version to. What if it's not the same version/format? Do we really need to have the prefix as part of the value? The reason the prefix was added was to be able to search on pseudonymized fields.

Based on the version and format in the extension a system should know what to do right?
![image](https://github.com/user-attachments/assets/ab9fd5ee-6eaf-4670-a87a-5b967b5768b7)

**Comment by bdc-ehealth** [comment]
@smals-stvar ,

a lot of the questions @smals-bvv is asking here are the result from your discussions with @hanndecl and @VirginieHayot . Can you clarify?

**Comment by smals-stvar** [comment]
I have not discussed this with @VirginieHayot and only briefly with @hanndecl. All the information I provide here is based on my own opinion.

Since the v2 format is more efficient (fewer bytes), the v1 format can be considered deprecated. In my view, given that pseudo-encrypted values are a new feature, there is no reason to support the v1 format for this purpose.

The prefix is added for convenience: FHIR is... complicated. I'm fairly certain that people will not check the extension and will instead parse the value to determine whether it is a pseudonym and which format it is. Yes, the information is duplicated, and it could lead to conflicts if the extension does not match the prefix. In such cases, I believe the server should return an error.

Even if you decide to remove the prefix from values in FHIR messages, it must still be kept for values defined in query parameters. Keeping the prefix for both ensures consistency, while removing it avoids discrepancies between the prefix and the extension.

**Comment by smals-bvv** [comment]
@bdc-ehealth will this be reviewed in a WG?

We still need to define a way to specify what version of pseudonyms a server should return in case of consultation by a client. In my opinion a client should be able to choose. This should be defaulting to v1 as this is the current published and used version.

**Comment by bdc-ehealth** [comment]
#draft# we propose to use an Accept-like header. The format of the accept header key will be specified in the IG. The default (in absence of the header) will be v1 without prefix. The Accept-like header will be mandatory if the version is not v1 without prefix.

**Comment by orophine** [comment]
What you could do is provide a call in the API to which you can call to receive the supported versions. And this technically means that as a developer you no longer need to know which version each API supports.
This way you ensure that no one uses versions that are not supported. 
And if you do not send a version to the API, then by default you should use the lowest possible version that your API supports. This way you ensure that your new APIs can only support version 2 or later. And this solution is also backwards compatible with version 1. And you do not need to agree on a default version

**Comment by costateixeira** [comment]
I think we should use CapabilityStatement as that API. 
The pseudo version could be in Rest.security.service, with a new valueset and codesystem for eHealth pseudonymization algorithms

**Comment by bdc-ehealth** [comment]
WG: we decide to adopt Benny's approach as described in https://github.com/hl7-be/infsec/issues/9#issuecomment-2421446102 as an addition to the headers described in https://github.com/hl7-be/infsec/issues/9#issuecomment-2393094293 . An example will be made using the input of the members of this group. We will notify the members if the example is ready, in order to comment.

**Comment by bdc-ehealth** [comment]
I removed invariant to force the key pseudonymisation to v2 in commit [f4b4077](https://github.com/hl7-be/infsec/pull/10/commits/f4b407796e4f9c4144c3bb81dfdbface2c1d36c8) , because the incentive to move to a higher version is already handled by Benny's approach https://github.com/hl7-be/infsec/issues/9#issuecomment-2421446102

**Comment by orophine** [comment]
I agree with the solution proposed in the email from Bart at 24/10/2024. I reviewed the example and that looks fine in mine opinion. Thank you for picking this up.
